### ISSUE TITLE
Droid.track() got an unexpected keyword argument 'mask'

### ISSUE THREAD

**Issue by StawEndl** [yufu-wang/tram#12]
hi, i got a problem when running the the process ,"python scripts/slam_video.py --video "./example_video.mov"".
there are the description of the error:
"""
Traceback (most recent call last):
  File "/home/ubuntu/mpz/tram-main/scripts/slam_video.py", line 56, in <module>
    droid, traj = run_slam(img_folder, masks=masks, calib=calib)
  File "/home/ubuntu/mpz/tram-main/scripts/../lib/pipeline/masked_droid_slam.py", line 145, in run_slam
    droid.track(t, image, intrinsics=intrinsics, depth=depth, mask=conf_msk)  
TypeError: Droid.track() got an unexpected keyword argument 'mask'
"""

the class Droid in the thirdparty/DROID-SLAM/droid_slam/droid.py have the fuction, track(self, tstamp, image, depth=None, intrinsics=None), which have no mask to accepted.

is there are something wrong when i clone the code? am i download the wrong version code?

**Comment by StawEndl** [comment]
sorry, i got the wrong code.
