### ISSUE TITLE
Has Droid-slam changed its source code?

### ISSUE THREAD

**Issue by 2022yingjie** [yufu-wang/tram#17]
Hi, thank you for your impressive work, when I tried to make a inference, there was an wired error showing as follows:
`Traceback (most recent call last):
  File "/mnt/fast_nas/xiyingjie/code/tram/scripts/estimate_camera.py", line 46, in <module>
    cam_int, is_static = calibrate_intrinsics(img_folder, masks, is_static=args.static_camera)
  File "/mnt/fast_nas/xiyingjie/code/tram/scripts/../lib/camera/masked_droid_slam.py", line 169, in calibrate_intrinsics
    best_err, is_static = test_slam(img_folder, input_msks, 
  File "/mnt/fast_nas/xiyingjie/code/tram/scripts/../lib/camera/masked_droid_slam.py", line 206, in test_slam
    droid.track(t, image, intrinsics=intrinsics, mask=conf_msk)  
TypeError: Droid.track() got an unexpected keyword argument 'mask'`

I check the droid's source code, it seems that its author changed the code, the corresponding code is:
`def track(self, tstamp, image, depth=None, intrinsics=None):
        """ main thread - update map """

        with torch.no_grad():
            # check there is enough motion
            self.filterx.track(tstamp, image, depth, intrinsics)

            # local bundle adjustment
            self.frontend()

            # global bundle adjustment
            # self.backend()`
 
is "masks" parameters important to the inference?

**Comment by yufu-wang** [comment]
Hi. We provided our own version of droid-slam [here](https://github.com/yufu-wang/tram/tree/0b1d84401d0843cc7f3fcae60ee9582277fc0316/thirdparty). If you clone our repo, you will get this one. 
The mask is important because we need to mask out the dynamic humans during slam.

**Comment by HugoXANA** [comment]
@yufu-wang hello,      
I reffered to the original repo of Droid-slam, and the original installation method indecates another conda env is needed for Droid-slam to be compiled. And thirdparty/DROID-SLAM/environment.yaml shows that it needs pytorch=1.10 which is not compatible with main repo install script install.sh(uses pytorch==2.0.0).      
So, how can we compile DROID-SLAM under conda env tram? Thank you!

**Comment by yufu-wang** [comment]
Very sorry for the late reply. Yes. you can compile DROID-SLAM under our suggested settings.
